Country.create!([
  {title: "France", image: "http://www.mapsofworld.com/images/world-countries-flags/france-flag.gif", gdp: "2.613 trillion USD", unemployment_rate: "10.4%", literacy_rate: "99%", military_budget: nil, minimum_wage: "12.79 USD per hour", average_age: "39.7", average_income: "54,600 USD", government_type: "Republic", head_of_state: "François Hollande", debt: "$1,982,593,508,025"},
  {title: "United Kingdom", image: "https://www.ivpn.net/blog/wp-content/img/uk-flag.jpg", gdp: "2.435 trillion USD", unemployment_rate: "6.6%", literacy_rate: "99%", military_budget: nil, minimum_wage: "10.63 USD per hour", average_age: "40.5", average_income: "44652.10 USD", government_type: "constitutional monarchy", head_of_state: "Queen Elizabeth II and David Cameron", debt: "$2,137,651,660,500"},
  {title: "Russia", image: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQqYOgTbViJ1BZRJaWv_ZTwAU-RLJYN7vgMZfUMcWRazts2YXCJ", gdp: "2.015 trillion USD", unemployment_rate: "5.5%", literacy_rate: "99.7%", military_budget: nil, minimum_wage: "1 USD per hour", average_age: "38.5", average_income: "17,230 USD", government_type: "federation", head_of_state: "Vladmir Putin", debt: "$226,620,229,117.353 USD"},
  {title: "China", image: "http://www.ultimateflags.com/images/P/buy_china_flag-01-01.gif", gdp: "8.227 trillion USD (2012)", unemployment_rate: "4.5%", literacy_rate: "95%", military_budget: nil, minimum_wage: "1.19 USD per hour", average_age: "35.2", average_income: "6,093", government_type: "Communist State", head_of_state: "Xi Jinping ", debt: "$5,101,946,956,217.09"},
  {title: "Afghanistan", image: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQSNv2zuvryEAESxHNvpNRiXKmjwZKd0023Rzmy1qvrC3_DqjtinQ", gdp: "18.03 billion USD", unemployment_rate: "50% ", literacy_rate: "28.1%", military_budget: nil, minimum_wage: ".5 USD per hour", average_age: "18", average_income: "426 USD", government_type: "Islamic republic", head_of_state: "Hamid Karzai", debt: "$1,280,000,000"},
  {title: "Australia", image: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTKge-AGY2vdNYNJwnWjfXn-3PQtxqiIr83SEEC1noof48qujzLuw", gdp: "1.521 trillion USD", unemployment_rate: "6.4%", literacy_rate: "96%", military_budget: nil, minimum_wage: "17.39 USD per hour", average_age: "37.5", average_income: "69,992 USD", government_type: "federal parliamentary democracy", head_of_state: "Queen Elizabeth II", debt: "$257,364,000"},
  {title: "North Korea", image: "http://www.themalaysianinsider.com/assets/uploads/articles/north-korea-flag-photos.jpg", gdp: "12.38 billion USD ", unemployment_rate: "Not Released", literacy_rate: "100%", military_budget: nil, minimum_wage: "Not Released", average_age: "33.9", average_income: "5,569 USD (Last data released in 1991)", government_type: "Dictatorship", head_of_state: "Kim Jong Un", debt: "$2,880,000,000"},
  {title: "Turkey", image: "https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/tu-lgflag.gif", gdp: "789.3 billion USD", unemployment_rate: "8.2%", literacy_rate: "95.3%", military_budget: nil, minimum_wage: "3.05 USD per hour", average_age: "28.1", average_income: "20,916 USD", government_type: "Republican parliamentary democracy", head_of_state: "Abdullah Gül", debt: "$386,786,000,000\t"},
  {title: "Uganda", image: "https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/ug-lgflag.gif", gdp: "19.88 billion USD", unemployment_rate: "4.2%", literacy_rate: "66.8%", military_budget: nil, minimum_wage: ".01 USD per hour", average_age: "15", average_income: "600 USD", government_type: "republic", head_of_state: "Yoweri Museveni", debt: "$4,126,000,000"},
  {title: "Somalia", image: "https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/so-lgflag.gif", gdp: "917 million USD", unemployment_rate: "67%", literacy_rate: "Not Released", military_budget: nil, minimum_wage: "Not Released", average_age: "17.6", average_income: "Not Released", government_type: "in the process of building a federal parliamentary republic", head_of_state: "Hassan Sheikh Mohamoud", debt: "$2,942,000,000\t"},
  {title: "South Korea", image: "https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/ks-lgflag.gif", gdp: "1.13 trillion USD", unemployment_rate: "2.7%", literacy_rate: "97.9%", military_budget: nil, minimum_wage: "4.63 USD per hour", average_age: "37.9", average_income: "29,308 USD", government_type: "republic", head_of_state: "Park Geun-hye", debt: "$436,900,000,000"},
  {title: "India", image: "https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/in-lgflag.gif", gdp: "1.842 trillion USD", unemployment_rate: "8.8%", literacy_rate: "74.4%", military_budget: nil, minimum_wage: ".28 USD per hour", average_age: "25.9", average_income: "1,116 USD", government_type: "federal republic", head_of_state: "Pranab Mukherjee and Narendra Modhi", debt: "376,000,000,000"},
  {title: "Germany", image: "https://www.cia.gov/library/publications/the-world-factbook/graphics/flags/large/gm-lgflag.gif", gdp: "3.4 trillion USD", unemployment_rate: "5.2%", literacy_rate: "99%", military_budget: nil, minimum_wage: "Not Released", average_age: "43.7", average_income: "30,721 USD per year", government_type: "federal republic", head_of_state: "Angela Merkel", debt: "$5,719,000,000,000"}
])
User.create!([
  {name: "Joesus", email: "josephbreen2016@northwestern.edu"},
  {name: "joejoejoejoe", email: "dfldfsdfls"}
])
